CREATE TABLE `users` (
  `U_ID` int NOT NULL AUTO_INCREMENT,
  `U_NOME` varchar(50) NOT NULL,
  `U_EMAIL` varchar(50) NOT NULL,
  `U_USERNAME` varchar(50) NOT NULL,
  `U_PASSWORD` varchar(256) NOT NULL,
  `U_AUTH_TOKEN` varchar(45) DEFAULT NULL,
  `U_AUTH_EXPDATE` datetime DEFAULT NULL,
  PRIMARY KEY (`U_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `carros` (
  `C_ID` int NOT NULL AUTO_INCREMENT,
  `U_ID` int DEFAULT NULL,
  `C_MARCA` varchar(50) NOT NULL,
  `C_POTENCIA` decimal(4,0) NOT NULL,
  `C_MODELO` varchar(50) NOT NULL,
  `C_COMBUSTIVEL` varchar(50) NOT NULL,
  `C_EXTRAS` varchar(100) NOT NULL,
  PRIMARY KEY (`C_ID`),
  KEY `FK_USERS_CARROS` (`U_ID`),
  CONSTRAINT `FK_USERS_CARROS` FOREIGN KEY (`U_ID`) REFERENCES `users` (`U_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4;